### ISSUE TITLE
Change casing in basic types to full lowercase.

### ISSUE THREAD

**Issue by Windows81** [CloneTrooper1019/clonetrooper1019.github.io#2]
Other keywords in your API dump, such as `bool` and `string`, are also written in full lowercase.  However, non-userdata object types such as `Array` and `Dictionary` are miscased.  As a precedent - in C#, most basic types are aliased in lowercase to maintain aesthetic consistency (you knew that already).

**Comment by CloneTrooper1019** [comment]
The typename being PascalCase is an artifact of what it’s written as in Roblox’s JSON API Dump.
